#! we may be needed to add environments for every service possible , and depends_on
version: '3'
services: 
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always # we always want traffic running
    build:
      dockerfile: Dockerfile.dev 
      context: ./nginx
    ports: 
      - '3050:80' # 3050 on the local machine and 80 on the container 
  client: 
    # without tty -- react app  will break on npm install command
    tty: true
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    # For time to time changes - -we use volumes
    volumes: 
      - /app/node_modules
      - ./client:/app 
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server 
    depends_on:
      - postgres
    # For time to time changes - -we use volumes
    volumes: 
      - /app/node_modules 
      - ./server:/app
    # Default environment variables for redis and pg images
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT= 6739
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker: 
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # For time to time changes - -we use volumes
    volumes: 
      - /app/node_modules
      - ./worker:/app 
  
